### PR TITLE
Code-Optimization

### PR DESCRIPTION
**Pull request by mdorenkamp**
The code has been checked with resharper, the changes made to the code contribute to readability and reflect recent language/compiler features

### CODE REVIEW

**Comment by jimradford** [comment]
@mdorenkamp while I do appreciate the efforts, I want to make sure we are still compatible with .NET 3.5. Using new language features is great if everyone is using the latest framework which I can assure you some are not. I haven't looked through all your changes yet but are you certain they meet the .NET 3.5 requirement and still compile and run under .NET 3.5?

Thanks!

**Comment by mdorenkamp** [comment]
i didnt change the target-framework, the only requirement i found is using the new roslyn compiler

**Comment by jimradford** [comment]
Great! Thanks again for the cleanup efforts. There are many more coming!

**Comment by mdorenkamp** [comment]
FYI: resharper still has ~2900 suggestions to improve code quality :)

**Comment by jimradford** [comment]
Oh I am sure it does, And I am sure at least a couple of them are good. Code readability = good, performance = good, some suggestions by automated tools make no sense to me. A-lot depends on personal style and styles inherited and learned along the way from other projects. One example is I believe code blocks inside of if statements should always be surrounded by {}, even though in my mind for a single line statement they are unnecessary.

**Comment by mdorenkamp** [comment]
i fully agree with that.

most of the changes regard naming-conventions and some "improvements" which are shorter in terms of "characters used" but are much more complicated to read.

ill generate a report with the problems (or what resharper sees as problems) identified. based on this we then can discuss which changes reasonable and which are not. is that ok for you? :)

**Comment by jimradford** [comment]
Sounds reasonable to me!

**Comment by mdorenkamp** [comment]
Here are the Optimizations suggested by Resharper

2707 issues found
- Codestyle(1517 issues 
	Add/remove this,' qualifier (1497 issues)
	Add/remove qualifier for static members (20 issues)
- Common Practices and Code Improvements (121 issues) 
	Auto-property can be made get-only (39 issues)
	Field can be made readonly (54 issues)
	Local variable has too wide declaration scope (3 issues) 
	Member can be made private (14 issues)
	Specify string culture explicitly (2 issues)
	String.Compare is culture-specific (1 issue)
	String.CompareTo is culture-specific (1 issue)
	String.IndexOf is culture-specific (6 issues)
	String.Lastlndex0f is culture-specific (1 issue)
- Constraints Violations (609 issues)
	Inconsistent Naming (603 issues)
	Possible null' assignment to entity with [NotNull] attribute (6 issues)
- Language Usage Opportunities (88 issues)
	'if' statement can be re-written as '??' expression (1 issue)
	Convert to lambda expression (1 issue)
	Loop can be converted into LINQ-expression (1 issue)
	Merge conditional?: expression into conditional access (6 issues)
	Merge sequential checks in && or || expressions (9 issues) 
	Replace if statement with null-propagating code (25 issues) 
	Use 'nameof expression to reference name (2 issues)
	Use string interpolation expression (42 issues)
– Potential Code Quality issues (176 issues)
	Access to modified closure (9 issues)
	Auto-property accessor is never used (5 issues)
	Cannot resolve symbolin text argument (1 issue)
	Delegate subtractions (1 issue)
	Elementis localizable (85 issues)
	Inconsistent synchronization on field (3 issues)
	Member hides static member from outer class (1 issue)
	Non-accessed field (9 issues)
	Non-readonly type member referenced in 'GetHashCodes' (4 issues) 
	Parameter hides member (2 issues)
	Possible System.InvalidCastException' in foreach loop (3issues)
	Possible 'System.InvalidOperationException' (1 issue)
	Possible System.NullReferenceException' (38 issues)
	Possible multiple enumeration of IEnumerable (2 issues)
	Possible unintended reference comparison (1 issue)
	Safe cast expression always succeeds (1 issue)
	String formatting method problems (3 issues)
	Type check and casts can be replaced with try cast (1 issue) 
	Virtual member call in constructor (6 issues)
– Redundancies in Code (99 issues)
	Assignment is not used (11 issues) 
	Explicit delegate creation expression is redundant (24 issues) 
	Private field can be converted to local variable (5 issues) 
	Redundant 'base.' qualifier (2 issues) 
	Redundant 'object.ToString' call (2 issues) 
	Redundant cast (12 issues) 
	Redundant control flow jump statement (2 issues) 
	Redundant empty default switch branch (3 issues) 
	Redundant lambda signature parentheses (12 issues) 
	Redundant name qualifier (26 issues)
– Redundancies in Symbol Declarations (97 issues) 
	Method return value is never used (4 issues)
	Non-accessed local variable (1 issue) 
	Redundant class or interface specification in base types list (1 issue) 
	Redundant member initializer (29 issues) 
	Redundant member override (1 issue) 
	Type or member is never used (39 issues) 
	Unused local variable (15 issues) 
	Unused parameter (7 issues)

A Detailed List can be found here: https://gist.github.com/mdorenkamp/0f265b0185ba30f150fc

**Pull request merged**
