### PR TITLE
Multi-Screen keyboard shortcuts

### PR DESCRIPTION
**Pull request by BastiG**
In my organization I'm working with multiple screens and prefer working with keyboard shortcuts as much as possible. Not being able to e.g. Win+Shift+Right while the PuTTY child window has the input focus has been a serious issue for me. So I extended the global shortcut handler with routines for Win+Shift+<Direction Keys> (change of screen) / Win+<Direction Keys> (Aero snap) - **primary feature in PR**.

Also, since we're using quite a large session list (2200+ entries) the tab context menu took about a second between right click and popping up. I changed the loading behavior for the tab context menu so it's built in the background - **2nd feature**.

That is when I realized that "Search as you type" won't work for me. For re-building the entire session tree on every keyboard press the control / data structure is simply not fast enough. Still I find it's quite a nice feature somebody might be interested in so I left the feature as an option in the PR - **3rd feature**.

I'm open for discussion, please reach out to me.

### CODE REVIEW

**Comment by jimradford** [comment]
Hi @BastiG 
I appreciate the efforts! I have quickly looked over the changes and I have a question and a request:

The question: Do these changes affect the current/default behaviour of the application or is it adding only new / optional features (e.g. does this fix bugs or does it add new functionality?).

The request:
I see you've included changes to the solution files and several .resx files which only seem to change versioning and do not appear to have any effect on the actual code you've submitted. Can you resubmit your PR without these changed files (or explain why they are needed).

Thanks,
Jim

**Comment by BastiG** [comment]
Hi @jimradford 
It's new features only, so I agree, the milestone seems a good fit.

I've noticed the changes to the resx files, too. To be honest I couldn't find a way to prevent them changing. I'll try to rebase into a fresh upstream master and see if I can make it work.

Cheers,
Sebastian

**Comment by BastiG** [comment]
New attempt with a revert of non-required changes, please let me know.

**Comment by jimradford** [comment]
@BastiG Thanks for taking the time to make those changes so quickly. I've merged in your changes for further testing. 1.5.0 is the next "planned" release. Until then binaries are available for anyone to test from the build server: https://ci.appveyor.com/project/jimradford/superputty/branch/master/artifacts 

For extra credit, feel free to submit relevant information on your feature to the Documentation page (on the wiki)

Thank you again for the effort!

**Pull request merged**
