### PR TITLE
Integration with Filezilla,winSCP, local/Remote Path, Encrypt ExtraArgs, filetransfer get the password from extraArgs.

### PR DESCRIPTION
**Pull request by bewaapps**
Integration with Filezilla,winSCP, local/Remote Path, Encrypt ExtraArgs, filetransfer get the password from extraArgs.
- Add local path and remote path in "Edit session" window (only works in Filetransfer and Filezilla)(4)
- Add integration with Filezilla and WinSCP to open sftp connection using superputty data (1)
- When open Filetransfer or Filezilla, get the password from ExtraArgs (if the ExtraArgs contains the password) (3)
- Hide the extra args if it contains command pw (3)
- Add the globalpassword for encrypt the extra arg password when importing/Exporting sessions (2 and 3)
- Encrypt the password included in the extraArgs when exporting sessions
- Decrypt the password included in the extraArgs when importing sessions
- Fix bugs in integration with filezilla
- Fix bug when select the exe files(when browse filezilla,winscp,mintty or pscp exe).
- Easy change the Aplication name

You can test all changes in https://github.com/bewaapps/superputty/tree/master

visualchangessuperputty

### CODE REVIEW

**Comment by joeyhub** [comment]
I suggest using pageant instead of passwords where possible. However, I occasionally put passwords in ExtraArgs.

My opinion on this set of modifications is that it is really specific to your needs. I have implemented something similar but do not consider it finished until I make it configurable and more abstract.

My extra programs open in an Open With submenu. In my case it is enough to have a system where you can add to a list of (Name, Path To Executable, Arguments Template). The arguments template would need to be able to take items from the session object (only host).

**Comment by bewaapps** [comment]
Hi jimradford, I'm agree with you, use plain text to store the master password is the worst option... but the most simple.. sorry, at the beginning, I only created that for export the xml sesions to other machines, and apply a little security level in the cases of I'm store the the password in the extra args . I'm working in a solution for that, I'm encrypting the master password with the current user. I'm using the ProtectedData https://msdn.microsoft.com/es-es/library/system.security.cryptography.protecteddata(v=vs.110).aspx.

in other hand, I'm in the same case of joeyhub, i use pageand, but occasionally i need store the password, and in this cases superputty saves this passwords in plain text, and i added a little security level for this cases.

The integration with filzilla and WinSCP are specific to my needs, I use this features every day (especially WinSCP with local and remote path). This solution offers an extra funcionality to superputty, and I think more people will be benefit from these changes. However i think the option of a really configurable extra programs is a good idea, but isn't the purpose of these changes. A mix of this idea is a include the "open with" option, with Filezilla and WinSCP, and when you has implemented your better feature, you can merge (or replace) with these changes.

Thanks for revise my code.
Best regards.

**Comment by bewaapps** [comment]
-- Add password encripted (only if master password isn't empty )  in sessions.xml.
-- Add window to select password when importing or exporting the sessions
-- Add alert message if the Extra Arguments contains the password.

newfeatures

**Comment by joeyhub** [comment]
Small typo here:
SingletonSesionPasswordManager

**Comment by bewaapps** [comment]
Hello @jimradford , if these changes are not in their merger plans, you could close this "pull request" please.
If you only want to combine some of the features of these changes, can suggest me please, and I could commit the changes indicated in another "pull request".
the features in this changes are:
- Integration with WinSCP and filezilla (works with pageant for secure connection)
- Local path and remote path in "Edit session" window (works in Filetransfer, winscp,filezilla)
- Filetransfer ,Winscp and Filezilla gets the password from ExtraArgs (if the ExtraArgs contains the password)
- Hide the extra args if it contains command pw.
- Change color of extra Args if contains pw in "Edit session" window.
- Add the Masterpassword (Encripted with the user data) for encrypt the extra arg password when save sessions
- Add window to select password for encrypt the password in ExtraArgs when export/import sessions. 
- Add alert if ExtraArgs contains a password.

**Comment by jimradford** [comment]
@bewaapps The only issues I have with this as it is are with the password encryption stuff. I don't want to yet get into the business of cryptography with SuperPuTTY. 

Even storing the passwords encrypted is not safe and gives the user a false sense of security since there is no way possible to keep them from showing up in the Windows processlist. I **strongly urge users to not use the -pw command line option!**. 

Even using SPSL is not secure since passwords are sent to the child window handle with the Windows Message system which of course can be accessed and viewed with a utility like spy++.

The only safe way to authenticate is using keys or of course typing your password each time.

With that said I have no problem with:

- [x] Integration with WinSCP and filezilla (works with pageant for secure connection)
- [x]  Local path and remote path in "Edit session" window (works in Filetransfer, winscp,filezilla)
- [x] Filetransfer ,Winscp and Filezilla gets the password from ExtraArgs (if the ExtraArgs contains the password)
- [ ] ~~Hide the extra args if it contains command pw.~~
- [x] Change color of extra Args if contains pw in "Edit session" window.
- [ ] ~~Add the Masterpassword (Encripted with the user data) for encrypt the extra arg password when save sessions~~
- [ ] ~~Add window to select password for encrypt the password in ExtraArgs when export/import sessions.~~
- [x] Add alert if ExtraArgs contains a password.

I do appreciate your efforts especially keeping your push current and ready to merge when its ready.

I am open to ideas and suggestions in regards to security

**Comment by bewaapps** [comment]
Hello @jimradford, I have deleted all references to encryption password, and I've merged with last version. if you have any suggestions or problem with this changes, let me know please.

Now only send the password to External apps and filetransfer, if the option AllowPlainTextPuttyPasswordArg is checked

**Comment by jimradford** [comment]
@bewaapps So I am not a git expert by any stretch of the imagination, but looking at what it "appears" this pull request is trying to do is undo 18 recent commits, then recommit them in addition to your changes. On your branch it shows you are 18 commits behind, and 19 ahead so something just doesn't look right to me. Maybe @joeyhub can comment on that. What I think needs to happen is your branch needs to be current with master, then a merge request with your local changes needs to be submitted. I have pending commits but I will save them until we can get your changes successfully integrated.

**Comment by jimradford** [comment]
@bewaapps what IDE are you using? with your patch applied Visual Studio 2015 is throwing an exception when I attempt to open any form in the form designer after applying your patch

Name cannot begin with the '<' character, hexadecimal value 0x3C. Line 155, position 2. 

I've spent an hour trying to resolve this but have not been able to determine which line 155 they are complaining about :) Its apparently in its XML parser. I've looked through and don't see anything obvious.

**Comment by bewaapps** [comment]
I use Visual Studio 2010,

**Comment by bewaapps** [comment]
I tried to reproduce the problem but I couldn't. I downloaded and installed the visual studio 2015, and I could open the solution and I could open all the forms in the form designer, I tried to clone my repository in other directory, and then, I tried again, but it doesn't throw any exception.

I commit a new change in xml settings, but i don't think this are the problem... :(

Do you have more information?

**Comment by jimradford** [comment]
@bewaapps with your last commit 76af7fe it seems to be fine now.

**Comment by bazinou** [comment]
Hi. How activate this functionnality on last Superputty release ? (1.4.0.8) ?
Thx

**Pull request merged**
