### PR TITLE
Added OpenBSD Puffy icon to default theme

### PR DESCRIPTION
**Pull request by vityank**
As described.

Icon info(Resized with small change to aspect ratio):
Source: https://www.openbsd.org/art/puffy/puf100X86.gif
Completely free to use according to:
https://www.openbsd.org/art4.html

### CODE REVIEW

**Comment by jimradford** [comment]
Hi @vityank would it be possible for you to utilize one of the icons from http://www.famfamfam.com/lab/icons/silk/ instead? We're already utilizing this iconset, its free and we have done the proper attribution.

**Comment by vityank** [comment]
Hi, @jimradford.
Thanks for the suggestion, of the current icons source.
I'll update the #794 in the evening, to replace my 'X' button with something like 'stop' one from Silk set.
Unfortunately they don't have Puffy for this PR :(

**Comment by jimradford** [comment]
@vityank  Hi Victor, what is it that puffy is supposed to represent in the application? Where is it being utilized, can you show a cropped screen capture for illustration?

Thanks for all the great work!

**Comment by vityank** [comment]
Hi,
It's actually like a 'tux' for Linux boxes, but to BSD folks. So user can mark his *BSD connections using puffy icon(We can't use daemon icon due to copyrights). While puffy is cpecifically OpenBSD's mascot, most BSD's users know or heart about other BSD's(There are 3 main OS's i the family).

Example screenshot(Within limits of 16x16, ofc)
image

**Comment by jimradford** [comment]
@vityank  got it! You're simply adding an option to better represent BSD Fans. Looks good. Now we'll need to find one for RDP. :)

**Pull request merged**
