### PR TITLE
fix problem for compiling with msbuild

### PR DESCRIPTION
**Pull request by NonProgrammerCharacter**
Fixed a problem for compiling with msbuild

### CODE REVIEW

**Comment by jimradford** [comment]
@NonProgrammerCharacter  Thanks for the pull request, but I do not understand how adding a setter affects msbuild?

**Comment by NonProgrammerCharacter** [comment]
@jimradford The build fails because it is not set, I just started learning C# so I propably cant explain it correctly but the msbuild error I get if it is not set is: CS0840 "'SuperPutty.ctlPuttyPanel.Session.get' is not marked as abstract or external and therefor has to declare a text. Automatically implemented properties need to have to define get- set- accessors."

**Comment by NonProgrammerCharacter** [comment]
I just read that this error only happens in old msbuild versions so it propably is not realy important.

**Comment by vityank** [comment]
Hi, I agree that this one is little problematic. I, myself need to apply simple patch before each build, because my environment is Win with .NET and bundled MSBuild(Yes, older one)+Portable WiX+Notepad++. No VS, or other useless, heavy junk. And the only one thing not supported by older MSBuild is the line from this bug. The only diff from reporter is that I think setter shall be private in this case(private set instead of set). If it doesn't hurt newer compilers, it will only help to build the app with less deps.
ctlPuttyPanel.cs(418,38): error CS0840: SuperPutty.ctlPuttyPanel.Session.get shall have body...

That's my 5c :)

**Pull request merged**
