### PR TITLE
Added preliminary limited support for RDP cand Win-Cmd connections.

### PR DESCRIPTION
**Pull request by vityank**
This is big WIP, part 1.
Adds initial RDP support as for #685 - Init/Middle state
Details:
1) Client first opens in full screen, Needs restore it to get SP catch it. - Need to investigate 
2) Hard to get the RDP window to be owned(parent-ed) by SP. This causes RDP clieet to left as external window, not tracked by SP. Only pos/size is somewhat changed
3) Flashing foreground icon of SP in taskbar then RDP is open - Fixed, but too many things rely on focus hijacking. Unfortunately for RDP focus track shall be disabled, or maybe enabled in very limited fasdhion(1 QPS).
Adds initial WinCmd support - Seems to be basically working.

Changes:
Connection Edit - Changed protocol selection from radio buttons to combobox. For VNC require the port and use RFC 5900 as default(Was blank previously).
For RDP also implemented import from OS recent terminal servers list import.

Challenges:
Make SP consistently and reliably take parentship of RDP process, while on the way taking parenthip of middle processes, especially "Auth Window" - Owning it helps to avoid it being minimized by OS.
The problem is with 2-nd and 3-rd windows while 3-rd is child of 2-nd and it's a final one. This nesting of windows in RDP causes the most headache, to make it work.
I'll need your advice, relying on your knowledge of code and hacks hidden inside windows and focus management. Thanks.
One of changes made is that id window is of 'dialog'
 type - no focus hijacking will be attempted on them, to allow user to enter info into those, w/o SP taking focus.

Rewrote to not touch the ReFocusPuTTY - only use the main first loop and extend time for RDP. Inheritance now works and foreground  tracing code is not disabled. However RDP "Auth" window now blocks the SP load till auth completes, so SP doesn't even fully draw till that.. Possibly the window searching part can be made threaded in the future... Also scroll-bars are missing from this internal window.

Need CR.

### CODE REVIEW

**Comment by jimradford** [comment]
I've played with this before and the extra windows were troublesome. A possible solution possibly: https://github.com/FreeRDP/FreeRDP. I *like* just managing external processes as we've done with putty, etc. I also like software that works and is predictable so we'll have to find the right balance. That being said Remote Desktop is as important of a tool for many including myself as an SSH terminal is.

I've merged in your changes and will myself be using this update and report back any trouble or additional thoughts. 

Thanks again @vityank this is a really cool feature to have.

**Comment by jimradford** [comment]
RDP - When double clicking top window bar or pressing alt+enter keys to go into full screen, RDP toolbar appears, Need to look into the possibility disabling this

image

**Comment by vityank** [comment]
I have quite a big list of thing which are problematic there.
1) If RDP is session windows is open in layout, then Auth window will lock SuperPutty's load on start-app - Loading will continue after auth.
FreeRDP is well known *nix client(Together with RDesktop) but was unmaintained for quite a long time. Win client still considered the best unfortunately.
2) There are lots of cases of some race-condition during connection opening. Only part of window get's into SP and scrollbars are missing.

3) While auth window is a problem the cause of most problems with off-client is second window which opens the final one with graphical session. This windows is hidden most of the time, but rarely you can see it - It has green progress bar of connection attempt.
May-be MS do it intentionally to increase security, by reducing chance of other software to intercept/wrap it's windows(With possible malicious intent of hijacking auth info)?

**Comment by vintprox** [comment]
I would love this feature very much! 😸 Already got annoyed by multiple RDP windows in task bar. Unfortunately for me, I bear no knowledge of how to test your stuff.

**Comment by vintprox** [comment]
You know what? Now it just takes only few clicks (with password typing ofc) to connect via RDP to every device in my catalog! Thank you very much for this pull request! Let me appretiate how it's more convenient than using this interface:
image

**Comment by Ala321** [comment]
HI, 
I have this error 
- System 

  - Provider 

   [ Name]  Application Error 
 
  - EventID 1000 

   [ Qualifiers]  0 
 
   Level 2 
 
   Task 100 
 
   Keywords 0x80000000000000 
 
  - TimeCreated 

   [ SystemTime]  2020-09-02T07:10:35.681953500Z 
 
   EventRecordID 8160 
 
   Channel Application 
 
   Computer DESKTOP
 
   Security 
 

- EventData 

   SuperPutty.exe 
   1.4.0.9 
   5bcf98fd 
   KERNELBASE.dll 
   10.0.18362.997 
   91b9349a 
   e0434352 
   000000000003a719 
   55c 
   01d680f8276d946f 
   C:\Program Files (x86)\SuperPuTTY\SuperPutty.exe 
   C:\WINDOWS\System32\KERNELBASE.dll 
   2b01717d-ee49-40b5-ab34-d65fdf3027b4

**Pull request merged**
