### PR TITLE
Improved desktop UI performance

### PR DESCRIPTION
**Pull request by joeyhub**
Superputty has a lot of performance problems related to scaling with many connections open and sessions. I have found that in some situations this impacts the rest of the system very badly.

I do not normally program in C# so this would benefit from a thorough review on standards.

This fix mitigates the problem by reducing the amount of interaction superputty has with the rest of the graphical system.

For every application container instantiated, SetWinEventHook was called for the range of events from EVENT_SYSTEM_FOREGROUND to EVENT_OBJECT_NAMECHANGE.

This is firstly inefficient because all of the hooks were global meaning that the hooks for each instance were identical duplicates. The cost of crossing the process boundary to is likely to be higher than the cost of using event listeners within the program to broadcast events.

The range of events was also 0x0003 to 0x800C meaning that most UI events would be captured including some that might be fired very frequently.

To solve this I made the hooks initialise once then provide an event handler accessible via the SuperPutty global class. I since improved this by allowing each Application Form instance to register the hooks needed for their child process filtering with the process id.

In profiling this patch reduced the number of event calls from 37500 (5.8%) in 60 seconds to 2800 (0.48%) in 15 minutes. I have further improved it since and expect an even lower call count with this patch.

Tests show that the system is still impacted by superputty (or possibly putty) but that this impact has been slightly reduced. This can be tested by moving a window and watching the framerate after loading a large number of connections. I am not sure if this problem manifests in all cases as it may depend on the other programs that are running.

I have also made some other improvements that are not yet submitted so it is hard to say how this patch impacts superputty performance in general. Some operations that were slow even with my latest changes now appear to be fast however I also cleaned up and minimised several configuration files which may have an impact as well.

I have additionally added a small fix for detecting putty/kitty command line errors by window title and a check to make sure that the putty window isn't initialised when it is not found. There are still a lot of potential issues with the Application Form and edge cases.

### CODE REVIEW

**Comment by joeyhub** [comment]
Please hold on merging this. There is a crash issue.

**Comment by joeyhub** [comment]
I think I have fixed the crash bug in the latest commit. It looks like it is a regression where .NET garbage collects the function wrapper.

I recommend thorough testing to be sure.

I have also added some simple handling for if the window is not found. I do not know if this is the best way to dispose of a process.

**Comment by joeyhub** [comment]
Please review and merge.

**Comment by jimradford** [comment]
Performance improvements are always welcome!

**Comment by jimradford** [comment]
Joey: Looks like you missed a file: 
Error	CS0246	The type or namespace name 'GlobalWindowEventArgs' could not be found (are you missing a using directive or an assembly reference?)...PuTTY\superputty\SuperPutty\ctlApplicationPanel.cs	198

**Comment by joeyhub** [comment]
The file is there but you need to manually add it from existing arguments in visual studio.

I had that same problem :D. I forgot to mention.

I'm not familiar with visual studio and after its conversion process to update the solution I thought it best to leave the bit to you.

**Comment by jimradford** [comment]
Gotcha, What version of Visual Studio are you using that required a conversion? I've unreverted the revert so your patches are now committed along with the addition of that file to the project file.

Thanks again
Jim

**Comment by joeyhub** [comment]
Community 2013, but now I've seen you do it I'll be able to do it next time manually or review the diff first.

**Pull request merged**
